"""Add Sample Plugin Demo Model

Revision ID: 51a9f1ab4b8b
Revises: 804b20c9599c
Create Date: 2023-06-04 21:30:37.777274

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '51a9f1ab4b8b'
down_revision = '804b20c9599c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samplepluginmodel',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_samplepluginmodel_conversation_id_conversation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_samplepluginmodel'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samplepluginmodel')
    # ### end Alembic commands ###
