version: '3'
services:
  guidance:
    image: paolorechia/guidance_server:gpu-0.3
    ports:
      - "9000:9000"
    volumes:
      - ./models:/models
    networks:
      common-network:
    # Add the "labels" section to set the container to remove itself on shutdown
    labels:
      - "com.docker.compose.container-name=guidance-server"
      - "com.docker.compose.service=guidance-server"
      - "com.docker.compose.oneoff=False"
      - "com.docker.compose.project=brainchulo-guidance-server"
    # Add the "stop_signal: SIGINT" option to use SIGINT signal for stopping the container gracefully
    stop_signal: SIGINT
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 28000M
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "7865:7865"
    networks:
      - common-network
    volumes:
      - ./app:/code
      - ./models:/models
    env_file:
      - .env
    # Add the "restart: unless-stopped" option to automatically restart the container unless explicitly stopped
    restart: unless-stopped
    # Add the "labels" section to set the container to remove itself on shutdown
    labels:
      - "com.docker.compose.container-name=backend"
      - "com.docker.compose.service=backend"
      - "com.docker.compose.oneoff=False"
      - "com.docker.compose.project=brainchulo-backend"
    # Add the "stop_signal: SIGINT" option to use SIGINT signal for stopping the container gracefully
    stop_signal: SIGINT


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - common-network
    volumes:
      - ./frontend:/code
      - /code/node_modules
    depends_on:
      - backend
    # Add the "restart: unless-stopped" option to automatically restart the container unless explicitly stopped
    restart: unless-stopped
    # Add the "labels" section to set the container to remove itself on shutdown
    labels:
      - "com.docker.compose.container-name=frontend"
      - "com.docker.compose.service=frontend"
      - "com.docker.compose.oneoff=False"
      - "com.docker.compose.project=brainchulo-frontend"
    # Add the "stop_signal: SIGINT" option to use SIGINT signal for stopping the container gracefully
    stop_signal: SIGINT
    entrypoint: ./entrypoint.sh
    env_file:
      - .env
networks:
  common-network:
    driver: bridge